//
// Created by sunxiaodong on 16/6/14.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#ifndef LOG_TAG
#define LOG_TAG "MY_JNI_LOG"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#endif
/* Header for class com_example_sunxiaodong_learnjni_MainActivity */

#ifndef _Included_com_example_sunxiaodong_learnjni_MainActivity
#define _Included_com_example_sunxiaodong_learnjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sunxiaodong_learnjni_MainActivity
 * Method:    getJniMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sunxiaodong_learnjni_MainActivity_getJniMessage
  (JNIEnv *env, jobject jObj) {
    LOGE("jni输出的log");
    return (*env).NewStringUTF("我的第一个Jni");
}

#ifdef __cplusplus
}
#endif
#endif